version: '3'

services:
  challenge-app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./:/usr/share/nginx
    networks:
      - challenge-network

  mysql-app:
    image: mysql:5.7.22
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: challenge
      MYSQL_ROOT_PASSWORD: laravel
    networks:
      - challenge-network

networks:
  challenge-network:
    driver: bridge
